### ISSUE TITLE
[Bug]: Plugins do not wor

### ISSUE THREAD

**Issue by JoaoNeto-ux** [ytmd-devs/ytmd#3986]
### Preflight Checklist

- [x] I use the latest version of YouTube Music (Application).
- [x] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [x] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.11.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.8.0

### Reproduction steps

I just open the app and no plugin works

### Expected Behavior

The SponsorBlock plugin, for example, should skip non-music segments

### Actual Behavior

It just doesn’t skip the segments nothing happens

### Enabled plugins

1. Sponsorblock

### Additional Information

The problem started on Windows 10 after I updated the app.
Later, I installed Windows 11, but the issue persisted.
I'm specifically referring to the SponsorBlock plugin, but I tested others as well and they also don't work, so it's not limited to just one plugin.
I’ve already disabled antivirus and other protections, downloaded older versions of the app, and even tried the portable version, none of them worked.

**Comment by ArjixWasTaken** [comment]
Just to verify, you mean to say that NO plugins work?

Like, not even synced lyrics?

**Comment by YivExe** [comment]
It seems that i'm having a similar problem, the problem on my side is that all of the plugins needs to be re-enabled without restarting the app itself, however this solution doesn't work with the download plugins, it keeps saying error d[...] is not a function

**Comment by ArjixWasTaken** [comment]
> It seems that i'm having a similar problem, the problem on my side is that all of the plugins needs to be re-enabled without restarting the app itself, however this solution doesn't work with the download plugins, it keeps saying error d[...] is not a function

Download plugin is broken due to YouTube changes

**Comment by JoaoNeto-ux** [comment]
> Just to verify, you mean to say that NO plugins work?
> 
> Like, not even synced lyrics?

The synced lyrics plugin works on its own. If I activate any other plugin, no lyrics appear, neither synced or static (I tested it with the plugin that switches between video and music, and the one that changes the theme color to match the album).
My biggest issue is with Sponsorblock, which I used the most.

**Comment by ArjixWasTaken** [comment]
Please gather logs when enabling sponsorblock and switching songs

**Comment by JoaoNeto-ux** [comment]
> Please gather logs when enabling sponsorblock and switching songs

How do I do this? I didn't find any text files with the logs

**Comment by ArjixWasTaken** [comment]
> > Please gather logs when enabling sponsorblock and switching songs
> 
> How do I do this? I didn't find any text files with the logs

You'll have to launch the app from the terminal and collect logs from there, and once the app is open, you have to also collect logs from the electron console (`Ctrl+Shift+I` and navigate to `console` tab)

**Comment by JoaoNeto-ux** [comment]
> > > Please gather logs when enabling sponsorblock and switching songs
> > 
> > 
> > How do I do this? I didn't find any text files with the logs
> 
> You'll have to launch the app from the terminal and collect logs from there, and once the app is open, you have to also collect logs from the electron console (`Ctrl+Shift+I` and navigate to `console` tab)

**Terminal:**
```
[YTMusic] i18n loaded
[YTMusic] Loading all plugins
[YTMusic] Plugin synced-lyrics::backend executed at 0.29ms
[YTMusic] Plugin in-app-menu::backend executed at 0.83ms
[YTMusic] Plugin auth-proxy-adapter::backend executed at 2.82ms
[YTMusic] Plugin "synced-lyrics::menu" loaded
[YTMusic] Plugin "auth-proxy-adapter::menu" loaded
[YTMusic] Plugin "synced-lyrics::menu" loaded
[YTMusic] Plugin "auth-proxy-adapter::menu" loaded
[YTMusic] ===========================================
[YTMusic] [Auth-Proxy-Adapter] Enable SOCKS proxy at socks5://127.0.0.1:4545
[YTMusic] [Auth-Proxy-Adapter] Using upstream proxy:
[YTMusic] ===========================================
Checking for update
Update for version 3.11.0 is not available (latest version: 3.11.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[YTMusic] Plugin sponsorblock::backend executed at 0.89ms
[YTMusic] Plugin "synced-lyrics::menu" loaded
[YTMusic] Plugin "auth-proxy-adapter::menu" loaded
```

**Console:**
```
music_polymer_inlined_html.js:4705 LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
youtube-music.iife.js:59 [YTMusic] Plugin synced-lyrics::renderer executed at 27.00ms
youtube-music.iife.js:1431 [YTMusic] Plugin "synced-lyrics" loaded
youtube-music.iife.js:59 [YTMusic] Plugin in-app-menu::renderer executed at 40.90ms
youtube-music.iife.js:1431 [YTMusic] Plugin "in-app-menu" loaded
watch?v=IB9y40nfSjU&list=QPdvGWKYvpaZ_zVuZeHnVjF5kLVZ2zWkbYL:1 [GroupMarkerNotSet(crbug.com/242999)!:A0402C00C4330000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader (about:flags#enable-unsafe-swiftshader) flag to opt in to lower security guarantees for trusted content.
youtube-music.iife.js:59 [YTMusic] Plugin sponsorblock::renderer executed at 0.20ms
youtube-music.iife.js:1431 [YTMusic] Plugin "sponsorblock" loaded
/watch?v=2h_xPuJ5dkI&list=QPdvGWKYvpaZ_zVuZeHnVjF5kLVZ2zWkbYL:1 [GroupMarkerNotSet(crbug.com/242999)!:A0402C00C4330000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader (about:flags#enable-unsafe-swiftshader) flag to opt in to lower security guarantees for trusted content.
```

**Comment by ArjixWasTaken** [comment]
And these are the only logs you get when using the app?

**Comment by JoaoNeto-ux** [comment]
> And these are the only logs you get when using the app?

Yes, I hope I did it correctly, but only these logs appeared. When I switch songs, nothing different shows up. A different message appeared when I opened the app with SponsorBlock already enabled, and when I press to disable it, this shows up:

```
[YTMusic] Failed to unload plugin "sponsorblock"
[YTMusic] Plugin "synced-lyrics::menu" loaded
[YTMusic] Plugin "auth-proxy-adapter::menu" loaded
Error: Failed to unload plugin "sponsorblock"
    at forceUnloadMainPlugin (file:///C:/Users/JoaoNeto/AppData/Local/Programs/youtube-music/resources/app.asar/dist/main/index.js:21959:26)
```
